アクセストークン更新バッチ処理追加

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -19,21 +19,30 @@ jobs:
       - restore_cache:
           paths: node_modules
           key: v1-dependencies-{{ checksum "package.json" }}
-      - run: *setup_puppeteer
+      - run:
+          name: Setup puppeteer
+          command: |
+            if [ -z "$PUPPETEER" ]; then
+              chmod +x ./setup_libxcb.sh
+              sh ./setup_libxcb.sh
+            fi
+      - run: yarn install
       - save_cache:
           paths: node_modules
           key: v1-dependencies-{{ checksum "package.json" }}
-      - run: yarn start
-      - store_artifacts:
-          path: ~/repo/loginpage.png
-          when: always
-      - store_artifacts:
-          path: ~/repo/mypage1.png
-          when: always
+      - run:
+          name: Execute task
+          command: |
+            if [ -z "$CI_TASK" ]; then
+              yarn task
+            else
+              echo "[ERROR] Undefined $CI_TASK"
+              exit 1
+            fi
 
-  batch:
+  update_access_token:
     docker:
-      - image: circleci/node:7.10
+      - image: circleci/node:8.9.4
     working_directory: ~/repo
     steps:
       - checkout
@@ -44,20 +53,20 @@ jobs:
       - save_cache:
           paths: node_modules
           key: v1-dependencies-{{ checksum "package.json" }}
-      - run: yarn start
+      - run: yarn update_token
 
 workflows:
   version: 2
-  ci_workflow:
+  task_workflow:
     jobs:
       - build
-  # batch_workflow:
-  #   triggers:
-  #     - schedule:
-  #         cron: "0 3,5,7,8,10,11,12,13,14 * * *"
-  #         filters:
-  #           branches:
-  #             only:
-  #               - master
-  #   jobs:
-  #     - batch
+  batch_workflow:
+    triggers:
+      - schedule:
+          cron: "0 1,3,5,7,9,11,13,15,17,19,21,23 * * *"
+          filters:
+            branches:
+              only:
+                - master
+    jobs:
+      - update_access_token
